# i3wm Core Settings
# Reference: http://i3wm.org/docs/userguide.html

# Modifier key (Mod4 = Super/Windows key)
set $mod Mod4

# Set display font
font pango:JetBrainsMono Nerd Font

# Drag floating windows using Mouse+$mod
floating_modifier $mod

# --- Giao diện: Khoảng cách & Viền ---

# Thêm khoảng cách giữa các cửa sổ (gaps)
gaps inner 6
gaps outer 2

# Bỏ viền (border) hoặc để viền thật mỏng (1px) trông sẽ hiện đại hơn
for_window [class="^.*"] border pixel 1

# Tự động ẩn khoảng cách & viền khi chỉ có 1 cửa sổ
smart_borders on
