# Định nghĩa biến màu (Catppuccin Mocha)
set $base     #1e1e2e
set $mantle   #181825
set $crust    #11111b
set $text     #cdd6f4
set $subtext0 #a6adc8
set $lavender #b4befe
set $blue     #89b4fa
set $sapphire #74c7ec
set $red      #f38ba8
set $peach    #fab387
set $yellow   #f9e2af

# Áp dụng màu cho cửa sổ (Border, Background, Text, Indicator, Child_border)
#                       border    backgr.   text    indicator child_border
client.focused          $lavender $base     $text   $peach    $lavender
client.focused_inactive $mantle   $base     $subtext0 $mantle   $mantle
client.unfocused        $mantle   $base     $subtext0 $mantle   $mantle
client.urgent           $red      $base     $text   $peach    $red
