# Mặc định của i3bar.
# Chúng ta sẽ vô hiệu hóa khối này để sử dụng Polybar.

# bar {
#         status_command i3status
# }

# Dự phòng khoảng cách phía trên cho Polybar (Floating Bar)
gaps top 22

# Tắt smart_gaps để luôn giữ khoảng cách bar ngay cả khi chỉ có 1 cửa sổ
smart_gaps off
