# --- Các cửa sổ luôn mở ở chế độ lơ lửng (Floating) ---
for_window [window_role="pop-up"] floating enable, sticky enable
for_window [title="Picture-in-Picture"] floating enable, sticky enable
for_window [window_role="task_dialog"] floating enable
for_window [class="Pavucontrol"] floating enable
for_window [class="Nm-connection-editor"] floating enable
for_window [class="Blueberry.py"] floating enable
for_window [class="feh"] floating enable

# Nổi các hộp thoại chọn file (File Picker/Chooser)
for_window [window_role="GtkFileChooserDialog"] floating enable
for_window [class="xdg-desktop-portal-gtk"] floating enable

# Ép Nổi tất cả các hộp thoại (dialogs/popups) mặc định
for_window [window_type="dialog"] floating enable
for_window [window_type="utility"] floating enable
for_window [window_type="toolbar"] floating enable
for_window [window_type="splash"] floating enable
for_window [window_type="popup_menu"] floating enable
for_window [window_type="menu"] floating enable
for_window [window_type="dropdown_menu"] floating enable
