# --- Các cửa sổ luôn mở ở chế độ lơ lửng (Floating) ---
for_window [window_role="pop-up"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [class="Pavucontrol"] floating enable
for_window [class="Nm-connection-editor"] floating enable
for_window [class="Blueberry.py"] floating enable
for_window [class="feh"] floating enable
