# Backend nên để là glx (GPU) thay vì xrender (CPU) để sửa lỗi giật lag của Alacritty
# backend = "glx";
# glx-copy-from-front = false;

# Tắt hiệu ứng fading (chớp) khi chuyển workspace hoặc chuyển cửa sổ
# fading = false;
# Nếu bạn muốn giữ fading nhưng không bị lỗi, hãy thử:
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;

